name: workout_player
description: Break - Break Your Fitness Goals

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.3.8

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  algolia: ^1.0.2
  animated_text_kit: ^4.2.1
  blurhash_dart: ^1.0.2
  cached_network_image: ^3.2.0 # no web
  circular_countdown_timer: ^0.2.0 # SHOULD REPLACE
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.10
  collection: ^1.15.0
  confetti: ^0.6.0
  cupertino_icons: ^1.0.3
  device_info_plus: ^3.1.1
  device_preview: ^1.0.0
  dotted_border: ^2.0.0 # SHOULD REPLACE
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.1 # SHOULD REPLACE
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.5.3 # no web
  firebase_storage: ^10.2.9
  fl_chart: ^0.46.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.6.0
  flutter_facebook_auth: ^3.5.6
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^1.0.1
  flutter_slidable: ^1.0.0-dev.9
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^1.0.3
  go_router: ^3.1.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  googleapis: ^7.0.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  kakao_flutter_sdk: ^1.1.1
  keyboard_actions: ^3.4.4
  logger: ^1.1.0
  material_floating_search_bar: ^0.3.6
  miniplayer: ^1.0.1 # SHOULD REPLACE
  mixpanel_flutter: ^1.3.1
  numberpicker: ^2.1.1 # SHOULD REPLACE
  percent_indicator: ^3.4.0 # SHOULD REPLACE
  reorderables: ^0.4.1
  rxdart: ^0.27.2
  shimmer: ^2.0.0 # SHOULD REPLACE
  sign_in_with_apple: ^3.2.0 # no web
  smooth_page_indicator: ^1.0.0+2
  table_calendar: ^3.0.3
  timeago: ^3.1.0 # SHOULD REPLACE
  url_launcher: ^6.0.12
  uuid: ^3.0.6
  visibility_detector: ^0.2.2
dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: "assets/logos/break_logo.png"
  image_path_android: "assets/logos/break_logo.png"
  andriod: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "#121212"

flutter:
  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: menlo
      fonts:
        - asset: assets/fonts/MenloRegular.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/emojis/
    - assets/svgs/
flutter_intl:
  enabled: true
