name: workout_player
description: Break - Break Your Fitness Goals

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.3.8

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # CORE
  flutter_svg: ^1.0.3
  logger: ^1.1.0
  uuid: ^3.0.6
  enum_to_string: ^2.0.1 # SHOULD REPLACE
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  cached_network_image: ^3.2.0 # no web

  # From Google or fluttercommunity.dev
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  url_launcher: ^6.0.12
  device_info_plus: ^3.1.1
  flutter_lints: ^1.0.4
  visibility_detector: ^0.2.2
  collection: ^1.15.0
  google_fonts: ^2.1.0
  flutter_blurhash: ^0.6.0
  googleapis: ^7.0.0

  # Firebase
  firebase_storage: ^10.0.6
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  cloud_functions: ^3.0.5
  firebase_auth: ^3.1.4
  firebase_crashlytics: ^2.2.4 # no web
  firebase_analytics: ^8.3.4

  # Authentication
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6
  sign_in_with_apple: ^3.2.0 # no web
  kakao_flutter_sdk: ^0.8.2

  # State Management
  flutter_riverpod: ^1.0.1
  get: ^4.3.8
  rxdart: ^0.27.2

  # Widgets
  algolia: ^1.0.2
  mixpanel_flutter: ^1.3.1
  flutter_slidable: ^1.0.0-dev.9
  fl_chart: ^0.46.0
  smooth_page_indicator: ^1.0.0+2
  circular_countdown_timer: ^0.2.0 # SHOULD REPLACE
  keyboard_actions: ^3.4.4
  flutter_rating_bar: ^4.0.0
  confetti: ^0.6.0
  numberpicker: ^2.1.1 # SHOULD REPLACE
  shimmer: ^2.0.0 # SHOULD REPLACE
  miniplayer: ^1.0.1 # SHOULD REPLACE
  percent_indicator: ^3.4.0 # SHOULD REPLACE
  table_calendar: ^3.0.3
  material_floating_search_bar: ^0.3.6
  reorderables: ^0.4.1
  dotted_border: ^2.0.0 # SHOULD REPLACE
  animated_text_kit: ^4.2.1
  blurhash_dart: ^1.0.2
  timeago: ^3.1.0 # SHOULD REPLACE
  flutter_sticky_header: ^0.6.0
  device_preview: ^1.0.0
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: "assets/logos/break_logo.png"
  image_path_android: "assets/logos/break_logo.png"
  andriod: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "#121212"

flutter:
  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: menlo
      fonts:
        - asset: assets/fonts/MenloRegular.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/emojis/
    - assets/svgs/
flutter_intl:
  enabled: true
